### PR TITLE
first commit

### PR DESCRIPTION
**Pull request by hovhannesyepremyan**

### CODE REVIEW

**Comment by VarduhiG** [comment]
Cannot run the program because the library(Text) cannot be found.
I even tried to install the library with pip3, but no result.

**Comment by hovhannesyepremyan** [comment]
Thanks for comment, Varduhi jan, I am confused, where did you see usage of text module?

**Comment by Sargis996** [comment]
Hovhannes jan neither I could find the code for Craps project

**Comment by hovhannesyepremyan** [comment]
Sargis jan, it has already been reviewed by 2 students and merged, so you can find it on MAIN branch.

**Comment by Sargis996** [comment]
ok Hovhannes jan

**Comment by VarduhiG** [comment]
The program is working!
All requirements are met even more!

The only comment:
Wording in output is a bit different than in the example provided.

**Comment by hovhannesyepremyan** [comment]
Thanks for comments Varduhi jan.

**Comment by VarduhiG** [comment]
Thanks to you!
Thank you for helping with GitHub!

**Pull request merged**
